### ISSUE TITLE
mybatis.config property conflicts with other properties in application.properties

### ISSUE THREAD

**Issue by boyazuo** [mybatis/mybatis-spring-boot#12]
When configed mybatis.config property, the other properties are ignored.

**Comment by eddumelendez** [comment]
Hi @boyazuo currently we can use xml or java config approach but not both of them at the same time in order to avoid mess.

**Comment by boyazuo** [comment]
I know that,but the configuration is not flexible. 
When I want to register plugin, I must use xml. and the other properties is not concise in xml.
I modify the code like this,and it work well,both xml and java config:
```
		if (StringUtils.hasText(this.properties.getConfig())) {
			factory.setConfigLocation(this.resourceLoader.getResource(this.properties.getConfig()));
		}
		factory.setTypeAliasesPackage(this.properties.getTypeAliasesPackage());
		factory.setTypeHandlersPackage(this.properties.getTypeHandlersPackage());
		factory.setMapperLocations(this.properties.getMapperLocations());
```

**Comment by eddumelendez** [comment]
In that case this is related to #7 I will work on this in order to provide more flexibility in java config.

**Comment by boyazuo** [comment]
Yes, it is great! I am looking forward to it.
And how is it going?

**Comment by eddumelendez** [comment]
@boyazuo support to register plugins has been added. I will close this issue.
