### ISSUE TITLE
 register plugins can't set properties of the plugins

### ISSUE THREAD

**Issue by boyazuo** [mybatis/mybatis-spring-boot#13]
```
factory.setPlugins(this.interceptors);
```
The plugins added.but can't set properties of the plugins.
so, exception will appear in the plugin,when application is running.

**Comment by liukaitj** [comment]
I think properties should be set in the plugin by itself via setProperties method which must be implemented according to the org.apache.ibatis.plugin.Interceptor contract.

ex:
```java
for (Interceptor interceptor : this.interceptors) {
  interceptor.setProperties(new Properties());
}
```

**Comment by eddumelendez** [comment]
Since register plugins was added. I think that the best way to inject properties is in the plugin by itself as @liukaitj said.
