### ISSUE TITLE
The file named spring.provider in mybatis-spring-boot-starter/src/main/resources/META-INF/

### ISSUE THREAD

**Issue by sunhao-java** [mybatis/mybatis-spring-boot#14]
What's this file means?The content is:
<code>
provides: mybatis-spring-boot-autoconfigure
</code>
Can u tell me?tks!

**Comment by eddumelendez** [comment]
This file is used to provide the **mybatis-spring-boot-autoconfigure** dependency without needing to add manually this dependency in the build file.

**Comment by sunhao-java** [comment]
thank u very much!
