### ISSUE TITLE
Could not open ServletContext resource [/mybatis-config.xml]

### ISSUE THREAD

**Issue by xiaoxing598** [mybatis/mybatis-spring-boot#15]
I will ```mybatis-config.xml``` profiling in ```src/main/resources/*```, When start being given ```Could not open ServletContext resource [/mybatis-config.xml]```
As can be seen from the annex screenshot Description
![qq 20160121135026](https://cloud.githubusercontent.com/assets/5615719/12474439/36ff8460-c056-11e5-91d2-f8b8adf750fe.png)

**Comment by zhuxinjun** [comment]
same problem...

**Comment by xiaoxing598** [comment]
我在想为什么作者还不回应一下呀？？？
（I wonder why the author does not respond to ah ???）

**Comment by zhuxinjun** [comment]
加 classpath; 在路径前边就可以了 @xiaoxing598

**Comment by xiaoxing598** [comment]
@zhuxinjun 
我又遇到一个严重的问题
mybatis.config=classpath:mybatis-config.xml

```
java.sql.SQLException: Driver:com.mysql.jdbc.Driver@7465364 returned null for URL:jdbc:h2:mem:testdb;DB_CLOSE_DELAY=-1;DB_CLOSE_ON_EXIT=FALSE
	at org.apache.tomcat.jdbc.pool.PooledConnection.connectUsingDriver(PooledConnection.java:326) ~[tomcat-jdbc-8.0.30.jar:na]
	at org.apache.tomcat.jdbc.pool.PooledConnection.connect(PooledConnection.java:200) ~[tomcat-jdbc-8.0.30.jar:na]
	at org.apache.tomcat.jdbc.pool.ConnectionPool.createConnection(ConnectionPool.java:708) [tomcat-jdbc-8.0.30.jar:na]
```

```
<?xml version="1.0" encoding="UTF-8" ?>
<!DOCTYPE configuration
        PUBLIC "-//mybatis.org//DTD Config 3.0//EN"
        "http://mybatis.org/dtd/mybatis-3-config.dtd">
<configuration>

    <typeAliases>
        <package name="com.example.domain"/>
    </typeAliases>

    <environments default="development">
        <environment id="development">
            <transactionManager type="JDBC"/>
            <dataSource type="POOLED">
                <property name="driver" value="com.mysql.jdbc.Driver"/>
                <property name="url"
                          value="jdbc:mysql://192.168.1.33:3306/test?useUnicode=true&amp;characterEncoding=utf8"/>
                <property name="username" value="test"/>
                <property name="password" value="test"/>
            </dataSource>
        </environment>
    </environments>

    <mappers>
        <mapper resource="com/example/mapper/CustomerMapper.xml"/>
    </mappers>

</configuration>
```

**Comment by eddumelendez** [comment]
@xiaoxing598 I would like to check the project. Can you share a sample project to reproduce the problem? Thanks

**Comment by xiaoxing598** [comment]
@eddumelendez I have put on the wrong platform project, please help view!
https://github.com/xiaoxing598/mybatis-spring-boot-example

**Comment by eddumelendez** [comment]
In a web application we must use **classpath:** prefix

```
spring.datasource.schema=classpath:import.sql
mybatis.config=classpath:mybatis-config.xml
```

**Comment by tspoison** [comment]
@xiaoxing598 你好，我看你上传的那个sample项目里在application.properties里和mybatis-config.xml里都配置了数据库连接的相关信息，两个地方配置有什么区别呢？不是很明白，请稍作解释，谢谢。
我在测试的过程中仅在application.properties里配置的话经测试可用。

**Comment by xiaoxing598** [comment]
@tspoison 你看我这个例子[https://github.com/xiaoxing598/mybatis-spring-boot-example](https://github.com/xiaoxing598/mybatis-spring-boot-example)

**Comment by tspoison** [comment]
@xiaoxing598 你刚上传的例子里怎么两个配置文件里的数据库连接信息都被注释了？

**Comment by DeadLion** [comment]
i met the same problem,add prefix classpath: wokrs
e.g
mybatis.config-location=classpath:mybatis-config.xml

**Comment by xiaoxing598** [comment]
@tianshuang 其实不用在它的配置文件里面再去配置数据库连接，因为他可以使用dataSource，所以你可以用某个连接池来配置。我目前在spring-boot + mybatis里面可以很好的工作。

**Comment by xiaoxing598** [comment]
@DeadLion I am in the `application.yaml` file as the following configuration is successful.
```
mybatis:
  config-location: "classpath:mybatis-config.xml"
```
I put `application.yaml` and `mybatis-config.xml` in the same file directory, They are all below resources.
