### ISSUE TITLE
How do i use the wildcard characters in mapperLocations

### ISSUE THREAD

**Issue by chw741852** [mybatis/mybatis-spring-boot#16]
In application.properties:
i want to use it like 'mybatis.mapper-locations[0]=classpath*:com/hong/**/mapper/*Mapper.xml' because i have many mapper.xml files, But spring throw an error, it didn't find the file '*Mapper.xml'.
i must use it like 'mybatis.mapper-locations[0]=com/hong/demo/UserMapper.xml'.

**Comment by xiaoxing598** [comment]
这块的文档确实很少

**Comment by chw741852** [comment]
Then I rewrite the SqlSessionFactory bean.
modify:
factory.setMapperLocations(new PathMatchingResourcePatternResolver()
                .getResources("classpath*:com/hong/**/mapper/*Mapper.xml"));
