### ISSUE TITLE
I can not  use both mybatis.config= and mybatis.mapperLocations=

### ISSUE THREAD

**Issue by ggj2010** [mybatis/mybatis-spring-boot#17]
if i use this config,
![qq 20160122184218](https://cloud.githubusercontent.com/assets/5978266/12508625/107b0566-c138-11e5-88e6-af0e50a539e4.png)

mybatis.mapperLocations and other config will not useful  

because of  mybatis.config has value

![qq 20160122184257](https://cloud.githubusercontent.com/assets/5978266/12508626/107b4922-c138-11e5-9300-b67330d462a0.jpg)

**Comment by xiemeilong** [comment]
+1
I have the same issue.

**Comment by eddumelendez** [comment]
As you can see, currently you can configure the project using xml or java config only. I would like to hear more about mixed support.

**Comment by kazuki43zoo** [comment]
fixed via https://github.com/mybatis/spring-boot-starter/pull/40.
