### ISSUE TITLE
Add support typeAliasesPackage & typeHandlersPackage

### ISSUE THREAD

**Issue by eddumelendez** [mybatis/mybatis-spring-boot#2]

**Comment by kazuki43zoo** [comment]
Hi @eddumelendez ,

I have a one question.
Have you plan to support VFS implementation for spring-boot ?
For details, refer to https://github.com/mybatis/mybatis-3/issues/325#issuecomment-132327054 .

**Comment by eddumelendez** [comment]
Thanks @kazuki43zoo to let me know about this. I will take a look and try to include in the first release.
