### ISSUE TITLE
Manual close is not allowed over a Spring managed SqlSession

### ISSUE THREAD

**Issue by zhuxinjun** [mybatis/mybatis-spring-boot#24]
![qq 20160226173736](https://cloud.githubusercontent.com/assets/7918671/13348661/b11c460a-dcaf-11e5-9b8a-214ddca4399c.png)

**Comment by s17t** [comment]
Hi, 
 this has been reported and closed in #9.

**Comment by eddumelendez** [comment]
@zhuxinjun if you test the snapshot you should not get this error.
