### ISSUE TITLE
could provide any example for interceptors added

### ISSUE THREAD

**Issue by bwzhang2011** [mybatis/mybatis-spring-boot#32]
@eddumelendez, would you mind providing us some interceptors configuration with mybatis spring boot as some example ?  from the simple example I could not find any info for such support, currently 
the sqlsessionfactory or sqlsessionTemplate creation has been replaced by mybatisAutoConfiguration
and the interceptors required default to be false which won't check whether in container or not.

**Comment by bwzhang2011** [comment]
@emacarron, would you mind sparing some time and take a look at it ? maybe more examples needed.

**Comment by bwzhang2011** [comment]
@eddumelendez, how could I delay the mybatisAutoConfiguration creation to make it later complete the initialization while other bean like interceptors or DatabaseIdProvider could first create themselves.

**Comment by eddumelendez** [comment]
@bwzhang2011 you can check [MybatisAutoConfigurationTest](https://github.com/mybatis/mybatis-spring-boot/blob/master/mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java) which provide cases you need.

**Comment by bwzhang2011** [comment]
@eddumelendez, thanks for quick response. yeah, I saw such test but I should find a proper way to load those beans which were initialized for mybatisAutoConfiguration. now I've the way that you should import such before the boot application started which means that you should first let those beans with interceptors or databaseIdProvider to be initialized first. just like this

1. the boot application 
@Import({ MybatisConfiguration.class })
@MapperScan(basePackages = { "com.mama100.platform.integr.sharding.mapper" })
@SpringBootApplication
public class ShardingMybatisBoot {
     public static void main(String[] args) {
		SpringApplication.run(ShardingMybatisBoot.class, args);

	}
}

2. the import source configuration class: 
@Configuration
public class MybatisConfiguration {

	@Bean
	public OffsetLimitDbInterceptorFactoryBean offsetInterceptor() throws Exception {
		OffsetLimitDbInterceptorFactoryBean interceptorFactoryBean = new OffsetLimitDbInterceptorFactoryBean();

		interceptorFactoryBean.setDbType(DataBaseType.MYSQL.getType());

		return interceptorFactoryBean;
	}

	@Bean
	public OptimistDbInterceptorFactoryBean optimistInterceptor() throws Exception {
		OptimistDbInterceptorFactoryBean interceptorFactoryBean = new OptimistDbInterceptorFactoryBean();

		interceptorFactoryBean.setDbType(DataBaseType.MYSQL.getType());

		return interceptorFactoryBean;
	}

	@Bean
	public DatabaseIdProvider databaseIdProvider() {
		VendorDatabaseIdProvider databaseIdProvider = new VendorDatabaseIdProvider();

		databaseIdProvider.setProperties(ShardingHelper.getVenderProperties());

		return databaseIdProvider;

	}
}

in real project you could not refer the test case idea which you should use annotationApplicationContext  to register the configuration that you should use @Import
