### ISSUE TITLE
How to declare interceptors for mybatis?

### ISSUE THREAD

**Issue by glenlivet** [mybatis/mybatis-spring-boot#37]
Thanks for creating this project. Can you make an example to show how to declare interceptors?

**Comment by eddumelendez** [comment]
You can check this test [MybatisAutoConfigurationTest](https://github.com/mybatis/mybatis-spring-boot/blob/master/mybatis-spring-boot-autoconfigure/src/test/java/org/mybatis/spring/boot/autoconfigure/MybatisAutoConfigurationTest.java#L189-L219)
