### ISSUE TITLE
dependency not found

### ISSUE THREAD

**Issue by ZhangMingNan** [mybatis/mybatis-spring-boot#6]

**Comment by hazendaz** [comment]
@ZhangMingNan what dependency is not found?

**Comment by s17t** [comment]
On Maven central there is the no-SNAPSHOT version only. The correct POM's snippet is:
```
<dependency>
    <groupId>org.mybatis.spring.boot</groupId>
    <artifactId>mybatis-spring-boot-starter</artifactId>
    <version>1.0.0</version>
</dependency>
```

**Comment by eddumelendez** [comment]
@s17t snapshots are in another repository in maven central. We will update the documentation in order to avoid confusion. Thanks.
