### ISSUE TITLE
Registering Plugin

### ISSUE THREAD

**Issue by patrek** [mybatis/mybatis-spring-boot#7]
Is there an easy way to register a Plugin (org.apache.ibatis.plugin.Interceptor) to the sqlSessionFactory with only java configuration?

**Comment by liukaitj** [comment]
This is an example which I use to register a pagination plugin ([PageHelper](https://github.com/pagehelper/Mybatis-PageHelper)) in pure Java config style. Though looks a bit bored, it's not so unacceptable in terms of the fact that you need to write it only once.
```java
	@Bean
	public SqlSessionFactory sqlSessionFactory(DataSource dataSource)
			throws Exception {
		SqlSessionFactoryBean sfb = new SqlSessionFactoryBean();
		sfb.setDataSource(dataSource);
		
		Properties prop = new Properties();
		prop.setProperty("dialect", "mysql");

		PageHelper pagePlugin = new PageHelper();
		pagePlugin.setProperties(prop);
			
		Interceptor[] plugins = {pagePlugin};
		sfb.setPlugins(plugins);
		
		SqlSessionFactory factory = sfb.getObject();
		factory.getConfiguration().setMapUnderscoreToCamelCase(true);
		return factory;
	}
```

**Comment by patrek** [comment]
Thanks.

Would have been nice if it was possible to do it by setting something in application.properties instead of overriding the bean creation.

**Comment by eddumelendez** [comment]
I am thinking to register all plugins automatically. Let try this approach. PR is welcome :)

**Comment by patrek** [comment]
I'll see what I can do this weekend :-)

**Comment by patrek** [comment]
Didn't get around to work in it yet.

While I'm at it, any idea of the best way to implement the configuration of settings the same way?

I've seen liukaitj's example about doing it. Is this the best approach? 
```java
SqlSessionFactory factory = sfb.getObject();
        factory.getConfiguration().setMapUnderscoreToCamelCase(true);
```
instead of using mybatis-config.xml
```
    <settings>
        <setting name="mapUnderscoreToCamelCase" value="true"/>
    </settings>
```

**Comment by mallim** [comment]
Actually if this works, why need to bring it inside?

````
 <settings>
        <setting name="mapUnderscoreToCamelCase" value="true"/>
    </settings>
````

The issue with #8 is it does not work by putting it in mybatis-config.xml

To quote the PageHelper example in here, I am doing this in mybatis-config.xml and it is working well:

````
    <plugins>
        <plugin interceptor="com.github.pagehelper.PageHelper">
            <property name="dialect" value="com.novacitynets.fornax.data.support.pagehelper.SqlServer2012Dialect"/>
        </plugin>
    </plugins>
````

**Comment by patrek** [comment]
As soon as you define mybatis-config.xml in the application.properties file, all other mybatis settings from that file are ignored.
