### ISSUE TITLE
How to set VendorDatabaseIdProvider?

### ISSUE THREAD

**Issue by mallim** [mybatis/mybatis-spring-boot#8]
Hi there

I will like to just set VendorDatabaseIdProvider to SqlSessionFactory, how should I go about doing it?

Currently, I work around by by setting it in mybatis-config.xml

````
    <databaseIdProvider type="DB_VENDOR">
        <property name="SQL Server" value="sqlserver"/>
        <property name="MySQL" value="mysql"/>
        <property name="Oracle" value="oracle" />
    </databaseIdProvider>
````

Thanks

**Comment by mallim** [comment]
With further testing, setting databseIdProvider in mybatis-config.xml is not working.

There is a need to allow VendorDatabaseIdProvider to be set.

**Comment by eddumelendez** [comment]
Take into account that the configuration just work with xml mappers or mapper annotations.

`databseIdProvider` is not available to auto-configure but the approach would be to provide the field `DatabaseIdProvider` to be autowired by any custom class and set the database vendors.

**Comment by mallim** [comment]
In view of this issue and issue #7, is it possible to have something like WebMvcConfigurerAdapter where we can extend the adapter and add in additional configurations to SqlSessionFactory?

**Comment by mallim** [comment]
Is the following code acceptable? If it is alright, I can submit a PR for further review.

````java
	@Bean
	@ConditionalOnMissingBean
	public SqlSessionFactory sqlSessionFactory(DataSource dataSource) throws Exception {
		SqlSessionFactoryBean factory = new SqlSessionFactoryBean();
		factory.setDataSource(dataSource);
		if (StringUtils.hasText(this.properties.getConfig())) {
			factory.setConfigLocation(
					this.resourceLoader.getResource(this.properties.getConfig()));
		} else {
			factory.setTypeAliasesPackage(this.properties.getTypeAliasesPackage());
			factory.setTypeHandlersPackage(this.properties.getTypeHandlersPackage());
			factory.setMapperLocations(this.properties.getMapperLocations());
		}

		// Try to locate for VendorDatabaseIdProvider bean
		try {
			VendorDatabaseIdProvider provider = BeanFactoryUtils.beanOfTypeIncludingAncestors(this.context, VendorDatabaseIdProvider.class);
			factory.setDatabaseIdProvider( provider );
			log.info( "Can locate VendorDatabaseIdProvider bean and using it");
		}
		catch( BeansException ex )
		{
			log.warn("Not setting VendorDatabaseIdProvider as the bean is not found");
		}

		return factory.getObject();
	}
````

**Comment by eddumelendez** [comment]
@mallim submit the PR for review. I will use @Autowired(required=false) rather than `BeanFactoryUtils.beanOfTypeIncludingAncestors(this.context, VendorDatabaseIdProvider.class);` and handle the exception.
